version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PUBLIC_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - soladia-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8008:8000"
    environment:
      - DATABASE_URL=postgresql://soladia:password@postgres:5432/soladia
      - SECRET_KEY=your-secret-key-here
      - DEBUG=false
    depends_on:
      - postgres
    networks:
      - soladia-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=soladia
      - POSTGRES_USER=soladia
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - soladia-network

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - soladia-network

volumes:
  postgres_data:

networks:
  soladia-network:
    driver: bridge
